version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports: ['5000:5000']
    volumes: ['.:/api']
  web_client:
    build:
      context: .
      dockerfile: ./apps/web_client/Dockerfile
    ports: ['5000:5000']
    volumes: ['.:/web_client']