version: '3'
services:
  api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
    ports: ['5000:5000']
    volumes: ['.:/rest_api']
  web_client:
    build:
      context: .
      dockerfile: web_client/Dockerfile
    ports: ['5000:5000']
    volumes: ['.:/web_client']